version: "3"
services:
  user-service:
    build: ./actorservice
    ports:
      - "8080:8080"
  order-service:
    build: ./movieservice
    ports:
      - "8081:8081"
    depends_on:
      - actorservice