version: "3"
services:
  actor-service:
    image: actor-service
    build:
      context: ./
    ports:
      - "8080:8080"

  movie-service:
    image: movie-service
    build:
      context: ./
    ports:
      - "8081:8081"
    depends_on:
      - actor-service